import net.fabricmc.loom.task.RemapJarTask
import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "com.mrcrayfish:framework-fabric:${minecraft_version}-${framework_version}"
    modCompileOnly ("dev.architectury:architectury-fabric:${architectury_api_version}") transitive false
    modCompileOnly ("mezz.jei:jei-${jei_minecraft_version}-fabric:${jei_version}") transitive false
    modCompileOnly ("dev.emi:emi-fabric:${emi_version}") transitive false
    modCompileOnly ("me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}") transitive false
    modCompileOnly ("me.shedaniel.cloth:cloth-config-fabric:18.0.145")
    //modRuntimeOnly "squeek.appleskin:appleskin-fabric:mc1.21.3-3.0.6"
    library include("com.mrcrayfish:controllable-sdl:${controllable_sdl_version}") {
        transitive false
    }
    implementation "com.google.code.findbugs:jsr305:3.0.1"
}

sourceSets.main.resources.srcDir 'src/generated/resources'

fabricApi {
    configureDataGeneration {
        outputDirectory.set(file("src/generated/resources"))
    }
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

remapJar {
    addNestedDependencies = false
}

tasks.register('releaseJar', RemapJarTask) {
    dependsOn tasks.jar
    input = tasks.jar.archiveFile
    addNestedDependencies = true
    archiveClassifier = 'release'
}
build.finalizedBy(releaseJar)

tasks.register("signJar") {
    dependsOn remapJar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = tasks.remapJar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}

build.dependsOn signJar

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
loom.remapConfigurations.configureEach {
    configurations.named(it.name) {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}