# Project
group=com.mrcrayfish

# Java
java_version=25

# Common
minecraft_version=26.1.2
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.145.4+26.1.2
fabric_loader_version=0.18.6
fabric_minecraft_version_range=~26.1-

# NeoForge
neoforge_version=26.1.2.4-beta
neoforge_version_range=[26.1.2,)
neoforge_loader_version_range=[2,)

# Mod options
mod_version=0.26.0
mod_name=Controllable
mod_author=MrCrayfish
mod_id=controllable
mod_desc=Adds the ability to use a controller to play Minecraft
mod_homepage=https://mrcrayfish.com/mods?id=controllable
mod_source=https://github.com/MrCrayfish/Controllable
mod_issues=https://github.com/MrCrayfish/Controllable/issues
mod_license=MIT

# Dependency options
controllable_sdl_version=2.32.10-1.1.0
framework_version=0.13.22
architectury_api_version=18.0.3
jei_version=29.5.0.24
jei_minecraft_version=26.1.2
emi_version=1.1.22+1.21.1
rei_version=21.9.812

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.caching=true