# Project
group=com.mrcrayfish

# Java
java_version=17

# Common
minecraft_version=1.20.4
neo_form_version=1.20.4-20240627.114801

# Forge
forge_version=49.1.0
forge_loader_version_range=[49,)
forge_version_range=[49,)
minecraft_version_range=[1.20.4, 1.21)

# Fabric
fabric_version=0.97.2+1.20.4
fabric_loader_version=0.16.10

# NeoForge
neoforge_version=20.4.239
neoforge_version_range=[20.4,)
neoforge_loader_version_range=[2,)

# Mod options
mod_version=0.21.4
mod_name=Controllable
mod_author=MrCrayfish
mod_id=controllable
mod_desc=Adds the ability to use a controller to play Minecraft
mod_homepage=https://mrcrayfish.com/mods?id=controllable
mod_source=https://github.com/MrCrayfish/Controllable
mod_issues=https://github.com/MrCrayfish/Controllable/issues
mod_license=MIT

# Dependency options
controllable_sdl_version=2.30.10-1.0.1
framework_version=0.7.12
jei_version=17.3.1.5
jei_minecraft_version=1.20.4
emi_version=1.1.19+1.20.4
rei_version=14.1.786
cloth_config_version=13.0.138
architectury_version=11.1.17

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false