# Project
group=com.mrcrayfish

# Java
java_version=21

# Common
minecraft_version=1.21.11
neo_form_version=1.21.11-20251209.172050

# Fabric
fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2

# NeoForge
neoforge_version=21.11.6-beta
neoforge_version_range=[21.11.,)
neoforge_loader_version_range=[2,)
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Mod options
mod_version=0.25.8
mod_name=Controllable
mod_author=MrCrayfish
mod_id=controllable
mod_desc=Adds the ability to use a controller to play Minecraft
mod_homepage=https://mrcrayfish.com/mods?id=controllable
mod_source=https://github.com/MrCrayfish/Controllable
mod_issues=https://github.com/MrCrayfish/Controllable/issues
mod_license=MIT

# Dependency options
controllable_sdl_version=2.32.10-1.1.0
framework_version=0.13.6
architectury_api_version=18.0.3
jei_version=27.3.0.14
jei_minecraft_version=1.21.11
emi_version=1.1.22+1.21.1
rei_version=21.9.812

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.caching=true