import org.apache.commons.io.FilenameUtils

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

sourceSets {
    test {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

configurations {
    testImplementation.extendsFrom implementation
    testRuntimeOnly.extendsFrom runtimeOnly
}

neoForge {
    enable {
        version = neoforge_version
        disableRecompilation = System.getenv("CI") == "true"
    }

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    mods {
        framework {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation "com.mrcrayfish:framework-neoforge:${minecraft_version}-${framework_version}"

    // JEI
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${jei_minecraft_version}-neoforge:${jei_version}"

    // EMI
    //compileOnly "dev.emi:emi-neoforge:${emi_version}"

    // Roughly Enough Items
    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"

    // AppleSkin
    //rumtimeOnly "squeek.appleskin:appleskin-neoforge:mc1.21.3-3.0.6"

    // Controllable SDL (https://github.com/MrCrayfish/ControllableSDL)
    library jarJar("com.mrcrayfish:controllable-sdl:${controllable_sdl_version}") {
        transitive(false)
    }


    testImplementation "org.junit.jupiter:junit-jupiter:5.7.2"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.register("signJar") {
    dependsOn jar
    onlyIf {
        findProperty('keyStore') || System.getenv("KEYSTORE")
    }
    doLast {
        def unsignedJar = tasks.jar.archiveFile.get().asFile
        def name = FilenameUtils.removeExtension(unsignedJar.getName())
        def signedJar  = layout.buildDirectory.file("libs/%s-signed.jar".formatted(name)).get().asFile
        def signingKeyAlias = findProperty('keyStoreAlias') ?: System.getenv("KEYSTORE_ALIAS")
        def signingKeystore = findProperty('keyStore') ?: System.getenv("KEYSTORE")
        def signingPassword = findProperty('keyStorePass') ?: System.getenv("KEYSTORE_PASS")
        ant.signjar(
            jar: unsignedJar,
            signedJar: signedJar,
            alias: signingKeyAlias,
            keyStore: signingKeystore,
            storePass: signingPassword,
            storetype: 'jks'
        )
        println "Signed jar created at: $signedJar"
    }
}

jar.finalizedBy 'signJar'

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

test {
    useJUnitPlatform()
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
